### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by qq854051086** [xenoscr/Atomic-Caldera#2]
Hello, I'm glad to see that someone has seen Caldera together. Can you share your use case?

**Comment by xenoscr** [comment]
Hello, sorry for the delay. My motives are pretty well spelled out in the readme and in the comments of the main Python file. I really just wanted to be able to build a more complete library of tests for Caldera and I intend to use Caldera to build and validate detection logic in a SOC environment. Having a large library of abilities will allow us to custom tailor adversaries to match our targeted threat actors.
